name: CSAIL
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - appnope=0.1.0=py37_0
  - astroid=2.3.3=py37_0
  - attrs=19.1.0=py37_1
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - ca-certificates=2019.11.27=0
  - certifi=2019.11.28=py37_0
  - cffi=1.12.3=py37hb5b8e2f_0
  - dbus=1.13.6=h90a0687_0
  - decorator=4.4.0=py37_1
  - defusedxml=0.6.0=py_0
  - deprecated=1.2.6=py_0
  - entrypoints=0.3=py37_0
  - expat=2.2.6=h0a44026_0
  - gettext=0.19.8.1=h15daf44_3
  - glib=2.56.2=hd9629dc_0
  - icu=58.2=h4b95b61_1
  - intel-openmp=2019.4=233
  - ipykernel=5.1.2=py37h39e3cac_0
  - ipython=7.8.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_0
  - isort=4.3.21=py37_0
  - jedi=0.15.1=py37_0
  - jinja2=2.10.1=py37_0
  - joblib=0.13.2=py37_0
  - jpeg=9b=he5867d9_2
  - jsonschema=3.0.2=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=5.3.1=py_0
  - jupyter_console=6.0.0=py37_0
  - jupyter_core=4.5.0=py_0
  - lazy-object-proxy=1.4.3=py37h1de35cc_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.16=h3efe00b_0
  - llvm-openmp=4.0.1=hcfea43d_1
  - markupsafe=1.1.1=py37h1de35cc_0
  - mccabe=0.6.1=py37_1
  - mistune=0.8.4=py37h1de35cc_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.14=py37h5e564d8_0
  - mkl_random=1.0.2=py37h27c97d8_0
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py37_0
  - ncurses=6.1=h0a44026_1
  - notebook=6.0.1=py37_0
  - numpy=1.16.5=py37hacdab7b_0
  - numpy-base=1.16.5=py37h6575580_0
  - openssl=1.1.1=h1de35cc_0
  - pandas=0.25.3=py37h0a44026_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.5.1=py_0
  - pcre=8.43=h0a44026_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=19.2.2=py37_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.9=py37_0
  - ptyprocess=0.6.0=py37_0
  - py4j=0.10.7=py37_0
  - pycparser=2.19=py37_0
  - pygments=2.4.2=py_0
  - pylint=2.4.4=py37_0
  - pynacl=1.3.0=py37h1de35cc_0
  - pyqt=5.9.2=py37h655552a_2
  - pyrsistent=0.14.11=py37h1de35cc_0
  - pyspark=2.4.4=py_0
  - python=3.7.4=h359304d_1
  - python-dateutil=2.8.0=py37_0
  - pytz=2019.2=py_0
  - pyzmq=18.1.0=py37h0a44026_0
  - qt=5.9.7=h468cd18_1
  - qtconsole=4.5.5=py_0
  - readline=7.0=h1de35cc_5
  - scikit-learn=0.21.3=py37h27c97d8_0
  - scipy=1.3.1=py37h1410ff5_0
  - send2trash=1.5.0=py37_0
  - setuptools=41.0.1=py37_0
  - sip=4.19.8=py37h0a44026_0
  - six=1.12.0=py37_0
  - sqlite=3.29.0=ha441bb4_0
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py37_0
  - tk=8.6.8=ha441bb4_0
  - tornado=6.0.3=py37h1de35cc_0
  - traitlets=4.3.2=py37_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - wheel=0.33.4=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - wrapt=1.11.2=py37h0b31af3_0
  - xz=5.2.4=h1de35cc_4
  - zeromq=4.3.1=h0a44026_3
  - zlib=1.2.11=h1de35cc_3
prefix: /anaconda3/envs/CSAIL

